language: python
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache:
  pip: true
install:
  - pip install mypy tox-travis codecov
script:
  - tox
  - mypy django_prices_openexchangerates --ignore-missing-imports
env:
  matrix:
    - DJANGO="2.2"
    - DJANGO="3.0"
    - DJANGO="master"
matrix:
  allow_failures:
    - python: "3.6"
      env: DJANGO="master"
    - python: "3.7"
      env: DJANGO="master"
    - python: "3.8"
      env: DJANGO="master"
after_success:
  - codecov
